// ─── Named re-exports ─────────────────────────────────────────────────────────
// Import only what you need — Rollup/Vite tree-shakes unused exports.
// Prefer: import { Mail, Check } from "@/lib/icons"

export {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  Ban,
  BarChart,
  BarChart3,
  Bot,
  Brain,
  Building2,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Clock,
  Code,
  Cog,
  Cookie,
  Copy,
  Cpu,
  Database,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  FileText,
  Gavel,
  Globe,
  GripVertical,
  Handshake,
  HelpCircle,
  History,
  Home,
  Hourglass,
  Info,
  Instagram,
  Lightbulb,
  Linkedin,
  List,
  Loader2Icon,
  LoaderCircle,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareText,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Music2,
  PanelLeft,
  Phone,
  PieChart,
  Plus,
  RefreshCw,
  Rocket,
  RotateCcw,
  Scale,
  Scissors,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Sun,
  Tag,
  Target,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  Users,
  X,
  Zap,
} from "lucide-react";

// ─── Dynamic icons bag ────────────────────────────────────────────────────────
// Only icons resolved by string name at runtime (Icons[s.icon] bracket access).
// Keep this slim — every entry is unconditionally bundled.
// Services:  Sparkles, Zap, TrendingUp, BarChart3, Globe, MessageCircle
// Cookies:   Info, List, Settings, ShieldCheck, Share2, RefreshCw, Mail
// About:     Eye, Handshake, Target

import {
  BarChart3,
  Eye,
  Globe,
  Handshake,
  Info,
  List,
  Mail,
  MessageCircle,
  RefreshCw,
  Settings,
  Share2,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Zap,
} from "lucide-react";

export const Icons = {
  BarChart3,
  Eye,
  Globe,
  Handshake,
  Info,
  List,
  Mail,
  MessageCircle,
  RefreshCw,
  Settings,
  Share2,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Zap,
} as const;

export type IconName = keyof typeof Icons;
