export const modalsPT = {
  // ── opções partilhadas entre os dois modais ──────────────────────────────────
  sourceOptions: [
    "Eventos", "Google", "Indicação", "Instagram", "LinkedIn",
    "Newsletter", "Pesquisa Orgânica", "Pinterest", "TikTok", "X", "Outros",
  ],

  // ── modal de contacto ────────────────────────────────────────────────────────
  contact: {
    closeLabel: "Fechar modal de contacto",
    title: "Vamos transformar o seu negócio juntos",
    description: "Partilhe os seus objetivos e a nossa equipa vai desenhar uma estratégia com IA para acelerar os seus resultados.",
    requiredFields: "Campos obrigatórios",
    fallback: "Não informado",
    subject: "Novo contacto",
    averageResponse: "Resposta média em menos de 48 horas úteis.",
    topicOptions: [
      "Contacto",
      "Criação de conteúdo",
      "Diagnóstico de negócio",
      "Dúvidas",
      "Parcerias",
      "Política de Cookies",
      "Serviços: IA",
      "Serviços: Automação",
      "Serviços: Crescimento",
      "Serviços: Dados & BI",
      "Serviços: Marketing Digital",
      "Serviços: Website",
      "Outros",
    ],
    labels: {
      name: "Nome *",
      email: "Email *",
      phone: "Telefone (opcional)",
      company: "Empresa (opcional)",
      source: "Como nos encontrou? (opcional)",
      topic: "Tema *",
      message: "Mensagem *",
    },
    placeholders: {
      name: "Ex: Ana Silva",
      email: "exemplo@empresa.com",
      phone: "+351 9XX XXX XXX",
      company: "Nome da empresa",
      source: "Selecione uma opção",
      topic: "Selecione o tema",
      message: "Conte-nos o que pretende transformar com IA...",
    },
    errors: {
      name: "Nome é obrigatório.",
      email: "Email é obrigatório.",
      topic: "Tema é obrigatório.",
      message: "Mensagem é obrigatória.",
      invalidEmail: "Insira um email válido.",
      form: "Reveja os campos obrigatórios e conclua a verificação antes de enviar.",
      turnstile: "Conclua a verificação de segurança antes de enviar.",
      turnstileExpired: "A verificação expirou. Por favor, confirme novamente.",
      turnstileError: "Não foi possível validar a verificação. Tente novamente.",
      submit: "Não foi possível enviar agora. Tente novamente em instantes.",
      missingPrefix: "Preencha os campos obrigatórios antes de enviar:",
    },
    submit: {
      idle: "Enviar mensagem",
      loading: "A enviar mensagem...",
      processing: "A processar...",
      success: "Mensagem enviada! Entraremos em contacto em breve.",
      successButton: "Transformação iniciada",
    },
  },

  // ── modal de newsletter ──────────────────────────────────────────────────────
  newsletter: {
    closeLabel: "Fechar modal da newsletter",
    badge: "Newsletter Sapiente.AI",
    title: "Registe-se na nossa newsletter",
    description: "Receba conteúdos sobre inteligência artificial, automação, marketing digital e formas práticas de tornar o seu negócio mais eficiente.",
    requiredFields: "Campos obrigatórios",
    optional: "(OPCIONAL)",
    subject: "Novo registo na newsletter - Sapiente.AI",
    labels: {
      name: "Nome",
      email: "Email",
      role: "Cargo",
      company: "Empresa",
      source: "Como nos encontrou?",
      accepted: "Li e compreendi a Política de Privacidade e autorizo o tratamento dos meus dados para receber comunicações da Sapiente.AI.",
    },
    placeholders: {
      name: "Ex: Ana Silva",
      email: "exemplo@empresa.com",
      role: "Ex: Diretora de Marketing",
      company: "Nome da empresa",
      source: "Selecione uma opção",
    },
    errors: {
      name: "Nome é obrigatório.",
      email: "Email é obrigatório.",
      invalidEmail: "Insira um email válido.",
      accepted: "Confirme a autorização para receber comunicações.",
      form: "Reveja os campos obrigatórios e conclua a verificação antes de enviar.",
      turnstile: "Conclua a verificação de segurança antes de enviar.",
      turnstileExpired: "A verificação expirou. Por favor, confirme novamente.",
      turnstileError: "Não foi possível validar a verificação. Tente novamente.",
      submit: "Não foi possível concluir o registo. Tente novamente em instantes.",
      missingPrefix: "Preencha os campos obrigatórios antes de se registar:",
    },
    submit: {
      idle: "Registar",
      loading: "A registar...",
      success: "Registo confirmado! Obrigado por se juntar a nós.",
    },
  },
} as const;
