export const modalsEN = {
  // ── shared options between both modals ───────────────────────────────────────
  sourceOptions: [
    "Events", "Google", "Instagram", "LinkedIn", "Newsletter",
    "Organic Search", "Pinterest", "Referral", "TikTok", "X", "Other",
  ],

  // ── contact modal ────────────────────────────────────────────────────────────
  contact: {
    closeLabel: "Close contact modal",
    title: "Let's transform your business together",
    description: "Share your goals and our team will design an AI-powered strategy to accelerate your results.",
    requiredFields: "Required fields",
    fallback: "Not provided",
    subject: "New contact",
    averageResponse: "Average response in less than 48 business hours.",
    topicOptions: [
      "Business diagnosis",
      "Contact",
      "Content creation",
      "Digital project",
      "Partnerships",
      "Questions",
      "Services: AI",
      "Services: Automation",
      "Services: Growth",
      "Services: Data & BI",
      "Services: Digital Marketing",
      "Services: Website",
      "Other",
    ],
    labels: {
      name: "Name *",
      email: "Email *",
      phone: "Phone (optional)",
      company: "Company (optional)",
      source: "How did you find us? (optional)",
      topic: "Subject *",
      message: "Message *",
    },
    placeholders: {
      name: "Ex: Anna Smith",
      email: "example@company.com",
      phone: "+351 9XX XXX XXX",
      company: "Company name",
      source: "Select an option",
      topic: "Select a subject",
      message: "Tell us what you want to transform with AI...",
    },
    errors: {
      name: "Name is required.",
      email: "Email is required.",
      topic: "Subject is required.",
      message: "Message is required.",
      invalidEmail: "Enter a valid email address.",
      form: "Please review the required fields and complete verification before sending.",
      turnstile: "Complete the security verification before sending.",
      turnstileExpired: "The verification expired. Please confirm it again.",
      turnstileError: "We couldn't validate the verification. Please try again.",
      submit: "We couldn't send your message right now. Please try again shortly.",
      missingPrefix: "Please fill in the required fields before sending:",
    },
    submit: {
      idle: "Send message",
      loading: "Sending message...",
      processing: "Processing...",
      success: "Message sent! We'll get back to you soon.",
      successButton: "Transformation started",
    },
  },

  // ── newsletter modal ─────────────────────────────────────────────────────────
  newsletter: {
    closeLabel: "Close newsletter modal",
    badge: "Sapiente.AI Newsletter",
    title: "Subscribe to our newsletter",
    description: "Get insights on artificial intelligence, automation, digital marketing, and practical ways to make your business more efficient.",
    requiredFields: "Required fields",
    optional: "(OPTIONAL)",
    subject: "New newsletter subscription - Sapiente.AI",
    labels: {
      name: "Name",
      email: "Email",
      role: "Role",
      company: "Company",
      source: "How did you find us?",
      accepted: "I have read and understood the Privacy Policy and authorize the processing of my data to receive communications from Sapiente.AI.",
    },
    placeholders: {
      name: "Ex: Anna Smith",
      email: "example@company.com",
      role: "Ex: Marketing Director",
      company: "Company name",
      source: "Select an option",
    },
    errors: {
      name: "Name is required.",
      email: "Email is required.",
      invalidEmail: "Enter a valid email address.",
      accepted: "Confirm authorization to receive communications.",
      form: "Please review the required fields and complete verification before sending.",
      turnstile: "Complete the security verification before sending.",
      turnstileExpired: "The verification expired. Please confirm it again.",
      turnstileError: "We couldn't validate the verification. Please try again.",
      submit: "We could not complete your subscription. Please try again shortly.",
      missingPrefix: "Please fill in the required fields before subscribing:",
    },
    submit: {
      idle: "Subscribe",
      loading: "Subscribing...",
      success: "Subscription confirmed! Thank you for joining us.",
    },
  },
} as const;
